spring.application.name=harmoGestionWeb
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
server.port=9003
fr.afpa.cda19.harmogestionweb.api-url=${HARMOGESTION_DB_URL}